# MPLAB IDE generated this makefile for use with GNU make.
# Project: Generador de funciones .mcp
# Date: Mon Apr 26 00:01:31 2021

AS = MPASMWIN.exe
CC = mcc18.exe
LD = mplink.exe
AR = mplib.exe
RM = rm

Practica\ 4.cof : Practica\ 4.o
	$(LD) /p16F877A "Practica 4.o" /u_DEBUG /z__MPLAB_BUILD=1 /z__MPLAB_DEBUG=1 /o"Practica 4.cof" /M"Practica 4.map" /W /x

Practica\ 4.o : Practica\ 4.asm ../../../../../../program\ files\ (x86)/microchip/mpasm\ suite/p16f877a.inc
	$(AS) /q /p16F877A "Practica 4.asm" /l"Practica 4.lst" /e"Practica 4.err" /d__DEBUG=1 /c-

clean : 
	$(RM) "Practica 4.o" "Practica 4.hex" "Practica 4.err" "Practica 4.lst" "Practica 4.cof"

